openapi: 3.0.0
info:
  title: Banking Microservice API
  description: Cloud-based banking microservice system
  version: 1.0.0
  contact:
    name: Banking API Support
    email: support@bankingapi.com

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.banking.com
    description: Production server

paths:
  /api/users/register:
    post:
      tags:
        - User Management
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - firstName
                - lastName
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                firstName:
                  type: string
                lastName:
                  type: string
                phone:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
        '409':
          description: User already exists

  /api/users/login:
    post:
      tags:
        - User Management
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

  /api/accounts:
    post:
      tags:
        - Account Management
      summary: Create a new account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - accountType
              properties:
                accountType:
                  type: string
                  enum: [checking, savings]
                initialDeposit:
                  type: number
                  minimum: 0
      responses:
        '201':
          description: Account created successfully

    get:
      tags:
        - Account Management
      summary: Get user accounts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user accounts
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Account'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        createdAt:
          type: string
          format: date-time

    Account:
      type: object
      properties:
        id:
          type: integer
        accountNumber:
          type: string
        accountType:
          type: string
          enum: [checking, savings]
        balance:
          type: number
        currency:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time